### ISSUE TITLE
test demo_06 issue

### ISSUE THREAD

**Issue by lkpnone** [systemd-learning/experiments#1]
1.lack experiments/download folder. After make, it will be failed when try to download kernel source.
2.Tool dependency: flex , bison , libssl-dev. Could wirte these tools dependency at README.md.
3.diskimg isn't big enough
+++ b/common/utils.sh
@@ -79,7 +79,7 @@ make_diskimg() {
        OUT_FILE=$3
 
        rm -f ${OUT_DIR}/${OUT_FILE}
-       dd if=/dev/zero of=${OUT_DIR}/${OUT_FILE} bs=1024k count=128
+       dd if=/dev/zero of=${OUT_DIR}/${OUT_FILE} bs=1024k count=512
        mkfs.ext4 -L ROOT ${OUT_DIR}/${OUT_FILE}
 
        TMP=`mktemp -d ./tmpd.XXX`

**Comment by taskset** [comment]
Thank you for your feedback！
